apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-lab
  labels:
    app: jenkins-lab
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jenkins-lab
  template:
    metadata:
      labels:
        app: jenkins-lab
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5001"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: jenkins-lab
        image: zeeker1/jenkins-lab:latest
        ports:
        - containerPort: 5001
        env:
        - name: BUILD_NUMBER
          value: "31"
